$(function () {
    var l = abp.localization.getResource('OpenId2Ids');
    var createModal = new abp.ModalManager(abp.appPath + 'Books/CreateModal');
    var editModal = new abp.ModalManager(abp.appPath + 'Books/EditModal');

    /* This file is automatically generated by ABP framework to use MVC Controllers from javascript. */


    // module app

    (function () {

        // controller abpSolution10.books.book

        (function () {

            abp.utils.createNamespace(window, 'tenark.books.book');

            tenark.books.book.get = function (id, ajaxParams) {
                return abp.ajax($.extend(true, {
                    url: window.remoteServiesPath + 'api/app/book/' + id + '',
                    type: 'GET'
                }, ajaxParams));
            };

            //tenark.books.book.getList = function (input, ajaxParams) {
            //    return abp.ajax($.extend(true, {
            //        url: window.remoteServiesPath + 'api/app/book' + abp.utils.buildQueryString([{ name: 'sorting', value: input.sorting }, { name: 'skipCount', value: input.skipCount }, { name: 'maxResultCount', value: input.maxResultCount }]) + '',
            //        type: 'GET'
            //    }, ajaxParams));
            //};


            tenark.books.book.getList = function (input, ajaxParams) {
                return {
                    "totalCount": 2,
                    "items": [
                        {
                            "name": "1984",
                            "type": 3,
                            "publishDate": "1949-06-08T00:00:00",
                            "price": 19.84,
                            "lastModificationTime": null,
                            "lastModifierId": null,
                            "creationTime": "2025-05-31T19:26:04.9596596",
                            "creatorId": null,
                            "id": "c9747a11-1d55-aa46-d323-3a1a398df36b"
                        },
                        {
                            "name": "The Hitchhiker's Guide to the Galaxy",
                            "type": 7,
                            "publishDate": "1995-09-27T00:00:00",
                            "price": 42,
                            "lastModificationTime": null,
                            "lastModifierId": null,
                            "creationTime": "2025-05-31T19:26:05.0089334",
                            "creatorId": null,
                            "id": "df68b413-2370-a19e-a01d-3a1a398df3d0"
                        }
                    ]
                }
            };


            tenark.books.book.create = function (input, ajaxParams) {
                return abp.ajax($.extend(true, {
                    url: window.remoteServiesPath + 'api/app/book',
                    type: 'POST',
                    data: JSON.stringify(input)
                }, ajaxParams));
            };

            tenark.books.book.update = function (id, input, ajaxParams) {
                return abp.ajax($.extend(true, {
                    url: window.remoteServiesPath + 'api/app/book/' + id + '',
                    type: 'PUT',
                    data: JSON.stringify(input)
                }, ajaxParams));
            };

            tenark.books.book['delete'] = function (id, ajaxParams) {
                return abp.ajax($.extend(true, {
                    url: window.remoteServiesPath + 'api/app/book/' + id + '',
                    type: 'DELETE',
                    dataType: null
                }, ajaxParams));
            };

        })();

    })();


    var dataTable = $('#BooksTable').DataTable(
        abp.libs.datatables.normalizeConfiguration({
            serverSide: true,
            paging: true,
            order: [[1, "asc"]],
            searching: false,
            scrollX: true,
            ajax: abp.libs.datatables.createAjax(tenark.books.book.getList),
            columnDefs: [
                {
                    title: l('Actions'),
                    rowAction: {
                        items:
                            [
                                {
                                    text: l('Edit'),
                                    visible: abp.auth.isGranted('Tenark.Books.Edit'), 
                                    action: function (data) {
                                        editModal.open({ id: data.record.id });
                                    }
                                },
                                {
                                    text: l('Delete'),
                                    visible: abp.auth.isGranted('Tenark.Books.Delete'), 
                                    confirmMessage: function (data) {
                                        return l('BookDeletionConfirmationMessage', data.record.name);
                                    },
                                    action: function (data) {
                                        tenark.books.book
                                            .delete(data.record.id)
                                            .then(function() {
                                                abp.notify.info(l('SuccessfullyDeleted'));
                                                dataTable.ajax.reload();
                                            });
                                    }
                                }
                            ]
                    }
                },
                {
                    title: l('Name'),
                    data: "name"
                },
                {
                    title: l('Type'),
                    data: "type",
                    render: function (data) {
                        return l('Enum:BookType.' + data);
                    }
                },
                {
                    title: l('PublishDate'),
                    data: "publishDate",
                    dataFormat: "datetime"
                },
                {
                    title: l('Price'),
                    data: "price"
                },
                {
                    title: l('CreationTime'), data: "creationTime",
                    dataFormat: "datetime"
                }
            ]
        })
    );

    createModal.onResult(function () {
        dataTable.ajax.reload();
    });

    editModal.onResult(function () {
        dataTable.ajax.reload();
    });

    $('#NewBookButton').click(function (e) {
        e.preventDefault();
        createModal.open();
    });
});
