apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-web-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ternark-web-portal
  template:
    metadata:
      labels:
        app: ternark-web-portal
    spec:
      containers:
      - name: ternark-web-portal
        image: tenark.azurecr.io/ternark-web-portal:v0.0.17
        env:
        - name: App__SelfUrl
          value: "https://localhost:44308"
        - name: RemoteServices__Default__BaseUrl
          value: "https://localhost:44370/"
        - name: ConnectionStrings__Default
          value: "Server=(LocalDb)\\MSSQLLocalDB;Database=Tenark;Trusted_Connection=True;TrustServerCertificate=True"
        - name: Redis__Configuration
          value: "127.0.0.1"
        - name: AuthServer__Authority
          value: "https://dev.tenark.com/authserver"
        - name: AuthServer__RequireHttpsMetadata
          value: "true"
        - name: AuthServer__ClientId
          value: "Tenark_Portal"
        - name: AuthServer__ClientSecret
          value: "1q2w3e*"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        resources:
          limits:
            cpu: "2"
            memory: "2048Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"