apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-web-portal
spec:
  template:
    spec:
      containers:
      - name: ternark-web-portal
        env:
        - name: App__SelfUrl
          value: "https://dev.tenark.com/portal"
        - name: RemoteServices__Default__BaseUrl
          value: "https://dev.tenark.com/httpapi-host/"
        - name: ConnectionStrings__Default
          value: "Server=tcp:tenark-sqlserver-dev.database.windows.net,1433;Initial Catalog=sqldb-tenark-tenant-common-dev;Persist Security Info=False;User ID=4dm1n157r470r;Password=sKaBq68#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        - name: Redis__Configuration
          value: "redis-tenark-tenant-common-dev.redis.cache.windows.net:6380,password=YPOztmqoqw0gDjQbrGnHTpDGDtyPWeE85AzCaJqSLpQ=,ssl=True,abortConnect=False"
        - name: AuthServer__Authority
          value: "https://dev.tenark.com/authserver"
        - name: AuthServer__RequireHttpsMetadata
          value: "true"
        - name: AuthServer__ClientId
          value: "Tenark_Portal"
        - name: AuthServer__ClientSecret
          value: "1q2w3e*"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"