apiVersion: batch/v1
kind: Job
metadata:
  name: tenark-dbmigrator
spec:
  template:
    spec:
      containers:
      - name: tenark-dbmigrator
        env: 
        - name: ConnectionStrings__Default
          value: "Server=tcp:tenark-sqlserver-dev.database.windows.net,1433;Initial Catalog=sqldb-tenark-tenant-common-dev;Persist Security Info=False;User ID=4dm1n157r470r;Password=sKaBq68#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        - name: IdentityServer__Clients__Tenark__ControlPlane__ClientId
          value: "Tenark_ControlPlane"
        - name: IdentityServer__Clients__Tenark__ControlPlane__ClientSecret
          value: "1q2w3e"
        - name: IdentityServer__Clients__Tenark__ControlPlane__RootUrl
          value: "https://dev.tenark.com/controlplane"
        - name: IdentityServer__Clients__Tenark__Tenark_Portal__ClientId
          value: "Tenark_Portal"
        - name: IdentityServer__Clients__Tenark__Tenark_Portal__ClientSecret
          value: "1q2w3e"
        - name: IdentityServer__Clients__Tenark__Tenark_Portal__RootUrl
          value: "https://dev.tenark.com/portal"
        - name: IdentityServer__Clients__Tenark__OpenId2Ids_Swagger__ClientId
          value: "OpenId2Ids_Swagger"
        - name: IdentityServer__Clients__Tenark__OpenId2Ids_Swagger__ClientSecret
          value: "1q2w3e"
        - name: IdentityServer__Clients__Tenark__OpenId2Ids_Swagger__RootUrl
          value: "44370"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"
      restartPolicy: Never
  backoffLimit: 4
