apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - post-processing-namespace.yml
  - post-processing-service.yml
  - post-processing-service-pod-identity.yml
  - post-processing-service-pod-identity-binding.yml