apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ternark-authserver
  template:
    metadata:
      labels:
        app: ternark-authserver
    spec:
      containers:
      - name: ternark-authserver
        image: tenark.azurecr.io/ternark-authserver:v0.0.17
        env:
        - name: App__SelfUrl
          value: "https://localhost:8081"
        - name: App__ClientUrl
          value: "http://localhost:4200"
        - name: App__CorsOrigins
          value: "https://*.OpenId2Ids.com,http://localhost:4200,https://localhost:44358,https://localhost:44370"
        - name: App__RedirectAllowedUrls
          value: "http://localhost:4200,https://localhost:44382,https://localhost:44358,https://localhost:44316"  
        - name: ConnectionStrings__Default
          value: "Server=(LocalDb)\\MSSQLLocalDB;Database=Tenark;Trusted_Connection=True;TrustServerCertificate=True"
        - name: Redis__Configuration
          value: "127.0.0.1"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"