apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-web-controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ternark-web-controlplane
  template:
    metadata:
      labels:
        app: ternark-web-controlplane
    spec:
      containers:
      - name: ternark-web-controlplane
        image: ternark-web-controlplane:1.0
        env:
        - name: App__SelfUrl
          value: "https://controlplane.tenark.com"
        - name: RemoteServices__Default__BaseUrl
          value: "https://dev.tenark.com/httpapi-host/"
        - name: ConnectionStrings__Default
          value: "Server=(LocalDb)\\MSSQLLocalDB;Database=Tenark;Trusted_Connection=True;TrustServerCertificate=True"
        - name: Redis__Configuration
          value: "redis-tenark-tenant-common-dev.redis.cache.windows.net"
        - name: AuthServer__Authority
          value: "https://dev.tenark.com/authserver"
        - name: AuthServer__RequireHttpsMetadata
          value: "true"
        - name: AuthServer__ClientId
          value: "Tenark_ControlPlane"
        - name: AuthServer__ClientSecret
          value: "1q2w3e*"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"