apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-httpapi-host
spec:
  template:
    spec:
      containers:
      - name: ternark-httpapi-host
        env:
        - name: App__CorsOrigins
          value: "*"
        - name: ConnectionStrings__Default
          value: "Server=tcp:tenark-sqlserver-dev.database.windows.net,1433;Initial Catalog=sqldb-tenark-tenant-common-dev;Persist Security Info=False;User ID=4dm1n157r470r;Password=sKaBq68#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        - name: Redis__Configuration
          value: "redis-tenark-tenant-common-dev.redis.cache.windows.net:6380,password=YPOztmqoqw0gDjQbrGnHTpDGDtyPWeE85AzCaJqSLpQ=,ssl=True,abortConnect=False"
        - name: AuthServer__Authority
          value: "https://dev.tenark.com/authserver"
        - name: AuthServer__RequireHttpsMetadata
          value: "true"
        - name: AuthServer__SwaggerClientId
          value: "OpenId2Ids_Swagger"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"