apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-httpapi-host
spec:
  template:
    spec:
      containers:
      - name: ternark-httpapi-host
        env:
        - name: App__CorsOrigins
          value: "*"
        - name: ConnectionStrings__Default
          value: "Server=(LocalDb)\\MSSQLLocalDB;Database=Tenark;Trusted_Connection=True;TrustServerCertificate=True"
        - name: Redis__Configuration
          value: "127.0.0.1"
        - name: AuthServer__Authority
          value: "https://dev.tenark.com/authserver"
        - name: AuthServer__RequireHttpsMetadata
          value: "true"
        - name: AuthServer__SwaggerClientId
          value: "OpenId2Ids_Swagger"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"