apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
patches: 
  - path: tenark-authserver-deployment.yaml
    target:
      kind: Deployment
      name: ternark-authserver