apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches: 
  - path: tenark-authserver-deployment-patch.yaml
    target:
      kind: Deployment
      name: ternark-authserver