apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-authserver
spec:
  template:
    spec:
      containers:
      - name: ternark-authserver
        env:
        - name: App__SelfUrl
          value: "https://dev.tenark.com/authserver"
        - name: App__ClientUrl
          value: "http://localhost:4200"
        - name: App__CorsOrigins
          value: "https://*.OpenId2Ids.com,https://*.authserver.tenark.com,http://localhost:4200,https://localhost:44358,https://localhost:44370"
        - name: App__RedirectAllowedUrls
          value: "http://localhost:4200,https://localhost:44382,https://localhost:44358,https://localhost:44316"  
        - name: ConnectionStrings__Default
          value: "Server=(LocalDb)\\MSSQLLocalDB;Database=Tenark;Trusted_Connection=True;TrustServerCertificate=True"
        - name: Redis__Configuration
          value: "redis-tenark-tenant-common-dev.redis.cache.windows.net:6380,password=YPOztmqoqw0gDjQbrGnHTpDGDtyPWeE85AzCaJqSLpQ=,ssl=True,abortConnect=False"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"