apiVersion: apps/v1
kind: Deployment
metadata:
  name: ternark-authserver
spec:
  template:
    spec:
      containers:
      - name: ternark-authserver
        env:
        - name: App__SelfUrl
          value: "https://dev.tenark.com/authserver"
        - name: App__ClientUrl
          value: "http://localhost:4200"
        - name: App__CorsOrigins
          value: "https://dev.tenark.com/*"
        - name: App__RedirectAllowedUrls
          value: "https://dev.tenark.com/authserver,https://dev.tenark.com/controlplane,https://dev.tenark.com/portal,https://dev.tenark.com/httpapi-host"  
        - name: ConnectionStrings__Default
          value: "Server=tcp:tenark-sqlserver-dev.database.windows.net,1433;Initial Catalog=sqldb-tenark-tenant-common-dev;Persist Security Info=False;User ID=4dm1n157r470r;Password=sKaBq68#;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        - name: Redis__Configuration
          value: "redis-tenark-tenant-common-dev.redis.cache.windows.net:6380,password=ixHxgIDElI6UcoX731KnxNDA3S3ysPEqJAzCaJiAbW4=,ssl=True,abortConnect=False"
        - name: StringEncryption__DefaultPassphrase
          value: "L0Dmme8ToNOlMMIu"
        # resources:
        #   limits:
        #     cpu: "2"
        #     memory: "2048Mi"
        #   requests:
        #     cpu: "0.5"
        #     memory: "512Mi"